create table public."InformacionGeneral_Cierres" (
  "Id_Viaje" bigint not null,
  "IDPedido" bigint null,
  "CargaViaje" double precision null,
  "IDPlanta" bigint null,
  "NombrePlantaViaje" text null,
  "IDUnidad" bigint null,
  "NombreUnidad" text null,
  "IDOperador" bigint null,
  "NombreOperador" text null,
  "IDEstatusViaje" bigint null,
  "NombreEstatus" text null,
  "FechaInicio" text null,
  "HoraInicio" text null,
  "HoraFin" text null,
  "IDObra" bigint null,
  "NombreObra" text null,
  "IDClienteSAE" bigint null,
  "NombreCliente" text null,
  "IDUso" bigint null,
  "NombreUso" text null,
  "IDProducto" bigint null,
  "NombreProducto" text null,
  "Remision" text not null,
  "CveCiudad" text null,
  "NombreVendedor" text null,
  constraint informaciongeneral_cierres_pkey primary key ("Id_Viaje", "Remision")
) TABLESPACE pg_default;