create table public."Proveedores" (
  "IdProveedor" bigint generated by default as identity not null,
  "NombreProveedor" character varying not null,
  constraint Proveedores_pkey primary key ("IdProveedor")
) TABLESPACE pg_default;