create table public."TanqueLecturas" (
  "IDTanqueLecturas" bigint generated by default as identity not null,
  "IDTanque" bigint null,
  "Fecha" date null,
  "Hora" time without time zone null,
  "LecturaCms" numeric(8, 2) null,
  "Temperatura" bigint null,
  "VolActualTA" bigint null,
  "VolActual15C" bigint null,
  "CuentaLitros" bigint null,
  "FechaRegistro" date null,
  "IDUsuarioRegistro" bigint null,
  "Activo" smallint null default '1'::smallint,
  constraint TanqueLecturas_pkey primary key ("IDTanqueLecturas"),
  constraint TanqueLecturas_IDTanqueLecturas_key unique ("IDTanqueLecturas")
) TABLESPACE pg_default;