create table public."TipoMovimiento" (
  "IdTipoMovimiento" bigint generated by default as identity not null,
  "Nombre" character varying not null,
  constraint TipoMovimiento_pkey primary key ("IdTipoMovimiento")
) TABLESPACE pg_default;